# Generated by Django 4.0.3 on 2023-09-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='General Inquiry', max_length=100),
        ),
    ]
